services:
  - type: web
    name: dolphin-backend
    env: php
    region: oregon
    branch: remove-docker-sail
    root: Dolphin_Backend
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader --no-interaction
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Dolphin
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: dolphin-backend
          property: host
      - key: FRONTEND_URL
        value: https://your-frontend.netlify.app
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      
      # Database configuration (using Render PostgreSQL)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: dolphin-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dolphin-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dolphin-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dolphin-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dolphin-db
          property: password
      
      # Mail configuration (add your mail service)
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: Dolphin
      
      # Stripe configuration
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  # PostgreSQL Database
  - name: dolphin-db
    databaseName: dolphin
    user: dolphin
    region: oregon
    plan: free
    ipAllowList: []
